In [ ]:
import pandas as pd

In [ ]:
ratings=[['John', 5,5,2,1], ['Mary', 4,5,3,2], ['Bob', 4,4,4,3], ['Lisa', 2,2,4,5], ['Lee', 1,2,3,4], ['Harry', 2,1,5,5,]]

In [ ]:
ratings

[['John', 5, 5, 2, 1],
 ['Mary', 4, 5, 3, 2],
 ['Bob', 4, 4, 4, 3],
 ['Lisa', 2, 2, 4, 5],
 ['Lee', 1, 2, 3, 4],
 ['Harry', 2, 1, 5, 5]]

In [ ]:
type(ratings)

list

In [ ]:
ratings[0]

['John', 5, 5, 2, 1]

In [ ]:
titles=['User', 'Jaws', 'Star Wars', 'Exorcist', 'Omen']

In [ ]:
titles

['User', 'Jaws', 'Star Wars', 'Exorcist', 'Omen']

In [ ]:
movies=pd.DataFrame(ratings, column=titles)

TypeError: DataFrame.__init__() got an unexpected keyword argument 'column'

In [ ]:
movies=pd.DataFrame(ratings, columns=titles)

In [ ]:
movies

User  Jaws  Star Wars  Exorcist  Omen
0   John     5          5         2     1
1   Mary     4          5         3     2
2    Bob     4          4         4     3
3   Lisa     2          2         4     5
4    Lee     1          2         3     4
5  Harry     2          1         5     5

In [ ]:
from sklearn import cluster

In [ ]:
data=movies.drop('User', axis=1)

In [ ]:
data

Jaws  Star Wars  Exorcist  Omen
0     5          5         2     1
1     4          5         3     2
2     4          4         4     3
3     2          2         4     5
4     1          2         3     4
5     2          1         5     5

In [ ]:
k_means=cluster.KMeans(n_clusters=2, max_iter=100, random_state=1)

In [ ]:
k_means

KMeans(max_iter=100, n_clusters=2, random_state=1)

In [ ]:
k_means.fit(data)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


KMeans(max_iter=100, n_clusters=2, random_state=1)

In [ ]:
labels=k_means.labels_

In [ ]:
labels

array([1, 1, 1, 0, 0, 0], dtype=int32)

In [ ]:
movies

User  Jaws  Star Wars  Exorcist  Omen
0   John     5          5         2     1
1   Mary     4          5         3     2
2    Bob     4          4         4     3
3   Lisa     2          2         4     5
4    Lee     1          2         3     4
5  Harry     2          1         5     5

In [ ]:
outcome=pd.DataFrame(labels, index=movies.User, columns=['Cluster ID'])

In [ ]:
outcome

Cluster ID
User             
John            1
Mary            1
Bob             1
Lisa            0
Lee             0
Harry           0

In [ ]:
k_means.cluster_centers_

array([[1.66666667, 1.66666667, 4.        , 4.66666667],
       [4.33333333, 4.66666667, 3.        , 2.        ]])

In [ ]:
import numpy as np

In [ ]:
testData=np.array([[4,5,1,2],[3,2,4,4],[3,2,4,1],[3,2,3,3],[5,4,1,4]])

In [ ]:
testData

array([[4, 5, 1, 2],
       [3, 2, 4, 4],
       [3, 2, 4, 1],
       [3, 2, 3, 3],
       [5, 4, 1, 4]])

In [ ]:
type(testData)

numpy.ndarray

In [ ]:
labels_test=k_means.predict(testData)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  warnings.warn(


In [ ]:
labels_test=k_means.predict(testData)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  warnings.warn(


In [ ]:
labels_test

array([1, 0, 1, 0, 1], dtype=int32)

In [ ]:
userNames=np.array(['Maina','Tom', 'Joyce', 'Kamau', 'Otieno', 'Will']).reshape(-1,1)

In [ ]:
userNames

array([['Maina'],
       ['Tom'],
       ['Joyce'],
       ['Kamau'],
       ['Otieno'],
       ['Will']], dtype='<U6')

In [ ]:
userNames.reshape(-1,1)

array([['Maina'],
       ['Tom'],
       ['Joyce'],
       ['Kamau'],
       ['Otieno'],
       ['Will']], dtype='<U6')

In [ ]:
userNames

array([['Maina'],
       ['Tom'],
       ['Joyce'],
       ['Kamau'],
       ['Otieno'],
       ['Will']], dtype='<U6')

In [ ]:
labels

In [ ]:
labels_test=labels_test.reshape(-1,1)

In [ ]:
labels_test

array([[1],
       [0],
       [1],
       [0],
       [1]], dtype=int32)

In [ ]:
cols=movies.columns.tolist()

In [ ]:
cols

['User', 'Jaws', 'Star Wars', 'Exorcist', 'Omen']

In [ ]:
cols.append('Cluster ID')

In [ ]:
cols

['User', 'Jaws', 'Star Wars', 'Exorcist', 'Omen', 'Cluster ID']

In [ ]:
newUsers = pd.DataFrame(np.concatenate((userNames, testData,labels_test), axis=1), columns=cols)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 6 and the array at index 1 has size 5